### PR TITLE
fix: set user's account data all at once

### LINKED ISSUE #97: Concurrent update issues for setting m.direct data
We are currently having concurrent update issues for different users where there are multiple rooms that are tried to set as `m.direct` concurrently, failing at the server as shown in the screenshot below.

### PR DESCRIPTION
**Pull request by Julieta11**
Closes #97 

We currently have concurrent update errors for different users when there are multiple rooms trying to set up `m.direct` on the initial sync.

So, to avoid the concurrent update error, we decided to set the user's `m.direct` events all at once with a single request, which allows us to lighten the number of updates and thus reduce the concurrent update error.

### CODE REVIEW

File: src/MessagingClient.ts [hunk 1]
```diff
@@ -67,14 +67,22 @@ export class MessagingClient implements MessagingAPI {
...
         const resolveOnSync = async (state: SyncState) => {
             if (state === 'SYNCING') {
+                const members: RoomMember[] = []
                 const rooms = this.getAllRooms()
                 const join: Promise<void>[] = rooms
                     .filter(room => room.getMyMembership() === 'invite') // Consider rooms that I have been invited to
                     .map(room => {
                         const member = room.getMember(this.socialClient.getUserId())
+                        if (member) {
+                            members.push()
```
Comment (guidota) [inline src/MessagingClient.ts:77]:
```suggestion
                            members.push(member)
```

**Comment by moliva** [comment]
Could we reproduce this with a test (and fix it)?

**Comment by Julieta11** [comment]
I couldn't reproduce the error with my user, from what I could see in the logs, the error happens to users who try to set up `m.direct` on the initial sync (cause they get a set new friendship requests) and happen to have many rooms in DirectRoomsMap (they have many friends). I was hoping to check the logs and see if anything changes tbh.

**Review by guidota — APPROVED** [review]
